blake-enyart/little-coffee-shop

meeting_minutes/20190401_Monday.md

Added minutes from today's group meeting. 🔢

Meeting minutes monday 20190401

---

.gitignore
Gemfile
Gemfile.lock
app/models/item.rb
app/models/order.rb
app/models/order_item.rb
app/models/user.rb
db/migrate/20190401224123_create_users.rb
db/migrate/20190401225337_create_orders.rb
db/migrate/20190401225925_add_orders_to_users.rb
db/migrate/20190402000942_create_items.rb
db/migrate/20190402023231_create_order_items.rb
db/migrate/20190402025636_add_items_to_users.rb
db/schema.rb
spec/models/item_spec.rb
spec/models/order_item_spec.rb
spec/models/order_spec.rb
spec/models/user_spec.rb
spec/rails_helper.rb

All, please review and let me know any comments.  Since this is such a large pull request and pretty pivotal to the remainder of the project, I think everyone should review it.  A couple notes:
- I used my judgement for the field names, I changed a couple from @n-flint schema.  If you think any should be renamed, comment on them with a suggested alternative.
- On the **User** table, I renamed the field **"username"** to **"name"**. @mikekarnes123 brought this up today but I believe the user story does ask for an actual name and you use an email to login.  So your email is basically a username and it makes more sense for this field to be a customer name.
- I was unsure if we wanted any validation tests for **OrderItem**.  We did not need to test the join table in the previous project but …

Database setup

---

app/controllers/application_controller.rb
app/controllers/cart_controller.rb
app/controllers/items_controller.rb
app/controllers/merchants_controller.rb
app/controllers/sessions_controller.rb
app/controllers/users_controller.rb
app/controllers/welcome_controller.rb
app/views/layouts/application.html.erb
config/routes.rb
spec/features/navigation_bar_spec.rb

- rspec - 100.00%
- rspec spec/models - 100.00%
registered navigation links
* description
closes #

Navigation setup

---

Gemfile
Gemfile.lock
spec/factories/item.rb
spec/factories/order.rb
spec/factories/order_item.rb
spec/factories/user.rb
spec/features/navigation_bar_spec.rb
spec/rails_helper.rb
spec/support/factory_bot.rb

Co-authored-by: Rene Casco <34440390+renecasco@users.noreply.github.com>
Co-authored-by: Michael Karnes <44683008+mikekarnes123@users.noreply.github.com>
Co-authored-by: Matt Levy <36040194+milevy1@users.noreply.github.com>
Co-authored-by: Blake Enyart <38588295+blake-enyart@users.noreply.github.com>
- rspec - 100%
- rspec spec/models - = 100%
had the wrong column name in the factories
* description
closes #
- [] I have commented my code, …

Added factorybot gem and factories for user, orders, items, order_items

---

app/controllers/application_controller.rb
app/controllers/merchants_controller.rb
app/views/layouts/application.html.erb
config/routes.rb
spec/features/navigation_bar_spec.rb

- rspec - 100%
Navigation bar for merchant
Sad path test(was out of scope)
* description
closes #77 

Navigation continued

---

app/controllers/application_controller.rb
app/controllers/merchants_controller.rb
app/controllers/sessions_controller.rb
app/views/layouts/application.html.erb
app/views/sessions/new.html.erb
config/routes.rb
spec/features/users/login_spec.rb

- rspec - 100%
- Create login functionality for user, merchant, and admin and direct to appropriate paths
Scoping the user story appropriately
* description
closes #69 
🙌

Pass User Story #10 to Create Login Functionality

---

app/views/layouts/application.html.erb

- rspec - x%
* description
closes #

Minor edit due to merge conflict

---

app/controllers/users_controller.rb
app/views/sessions/new.html.erb
app/views/users/new.html.erb
config/routes.rb
spec/features/users/registration_spec.rb

- rspec - 99.65%
Create a new user and saves to the database
Implementation of build from Factorybot versus Create
Use of POST in form_for directed to weird error.
* description
closes #73 
👍

Create registration functionality from User Story #7

---

app/controllers/admin/users_controller.rb
app/controllers/application_controller.rb
app/views/layouts/application.html.erb
config/routes.rb
spec/features/navigation_bar_spec.rb

- rspec - 100%
Admin navigation
routing for admin dashboard
* description
closes #76 

Admin navigation

---

spec/features/users/registration_spec.rb

Co-authored-by: Noah Flint <34421236+n-flint@users.noreply.github.com>
- rspec - 100%
Ensures user correctly fills out registration form
Nada
* description
closes #72 
💯

Complete User Story #8 for User Registration Missing Details

---

app/controllers/users_controller.rb
spec/features/users/registration_spec.rb

Co-authored-by: Noah Flint <34421236+n-flint@users.noreply.github.com>
- rspec - 100%
Creates safeguards for registering a new user
nada
* description
closes #72 

Complete User Story #8

---

app/controllers/admin/users_controller.rb
app/controllers/cart_controller.rb
app/controllers/merchants_controller.rb
app/controllers/users_controller.rb
spec/features/users_cannot_navigate_to_certain_paths_spec.rb

- rspec - 99.72%
Added restrictions for certain users to view certain url paths.  There could potentially be more as we add more pages, especially in the admin namespace, but we will address those we build them.  This PR restricts all the currently existing pages.
* description
closes #75 
💯

Users cannot navigate to certain paths #75

---

app/controllers/users_controller.rb
app/views/users/new.html.erb
spec/features/users/registration_spec.rb

- rspec - 100%
Create error message specifically for when a user tries to register with email that has been used
Boolean statement for showing just the error for the email
* description
closes #71 
👍

Complete User Story 9 Unique Email Functionality

---

app/controllers/sessions_controller.rb
spec/features/users/login_spec.rb

- rspec - 100%
Protects login form against invalid email or password
nada
* description
closes #68 
😃

Pass User Story 11 - User Cannot Log In with Bad Credentials

---

app/controllers/sessions_controller.rb
spec/features/users/login_spec.rb
spec/features/users/logout_spec.rb

- rspec - 100%
Creates logout functionality
Nada
* description
closes #66 
💯

Complete User Story 13 - Creates Logout Functionality -  issue #66

---

app/controllers/application_controller.rb
app/controllers/cart_controller.rb
app/controllers/items_controller.rb
app/models/cart.rb
app/views/items/show.html.erb
app/views/layouts/application.html.erb
config/routes.rb
spec/features/cart/add_items_to_cart_spec.rb
spec/models/cart_spec.rb

- rspec - 100%
Added Cart functionality.  I followed the class lesson plan to implement and mimicked the syntax.  Please reference the class lesson for questions first.  If you still have questions, let me know. http://backend.turing.io/module2/lessons/cart_implementation
- Includes ability to add items to Cart and all requirements for User Story 20.  
- Also adds Cart counter to nav bar
* description
closes #56 
👻

Cart adding items userstory20 #56

---

Gemfile.lock
app/controllers/items_controller.rb
app/models/item.rb
app/views/items/show.html.erb
spec/features/items/show_spec.rb
spec/models/item_spec.rb

- rspec - 100%
Item show page
* description
closes #62 
💯

Item show page

---

app/controllers/users_controller.rb
app/views/users/show.html.erb
config/routes.rb
spec/features/reg_users/profile_show_spec.rb

- rspec - 100%
Create user show page
nada
* description
closes #60 
😹

Pass User Story 17 - User Profile Show Page

---

app/models/cart.rb
app/models/item.rb
app/views/cart/index.html.erb
spec/features/cart/view_cart_with_items_spec.rb
spec/models/cart_spec.rb
spec/models/item_spec.rb

- rspec - 100%
Added Cart index page for user story 21.  Includes two Cart instance methods and one Item instance method to push calculations to the model and clean up the view.  If there are a lot of questions, I can review this with the team tomorrow.
* description
closes #55 
My gift to you @blake-enyart 🎁

User views cart with items userstory21 #55

---

app/models/item.rb

- rspec - 100%
Hotfix, joins was missing an 's'
* description
closes #

Added s to joins

---

app/controllers/users_controller.rb
spec/features/reg_users/profile_spec.rb

- rspec - 100%
Test for password mismatches in edit functionality for user profile details
nada
* description
closes #59 
😫

Bte password mismatch #59

---

app/controllers/cart_controller.rb
app/models/cart.rb
app/views/cart/index.html.erb
spec/features/cart/view_cart_when_empty_spec.rb
spec/features/cart/view_cart_with_items_spec.rb
spec/models/cart_spec.rb

- rspec - 100%
User Story 22 - User views their cart show page but it's empty. 
- Shows a message that their cart is empty. 
- Does not show link to empty cart
- Does not show grand total
* description
closes #54 
💤

User views empty cart userstory22 #54

---

app/controllers/users_controller.rb
app/models/user.rb
spec/features/reg_users/profile_spec.rb
spec/models/user_spec.rb

- rspec - 100%
Create validation of user email is unique on editing
Writing good code. We need help finding better ways to refactor our code in the user controller and user model because the code is kind of gross right now.
* description
closes #58 
🐉 🔥

Pass User Story 19 - Editing Profile Data must be unique email

---

app/models/user.rb

- rspec - x%
* description
closes #

Quick addition of end to user model

---

app/controllers/cart_controller.rb
app/views/cart/index.html.erb
config/routes.rb
spec/features/cart/user_can_empty_cart_spec.rb

- rspec - 100%
- rspec spec/models - 97.21%
Adds User Story 23, User can empty a cart that has items
* description
closes #53 
💔

User can empty cart userstory23 #53

---

app/controllers/admin/merchants_controller.rb
app/views/admin/merchants/show.html.erb
spec/features/admins/merchant_downgrade_spec.rb

- rspec - 100%
If an admin attempts to visit the merchant show of a user(not merchant) then they are redirected to user show of that user 
* description
closes User story 60
yep-> Some Tests have been changed
yep-> My code has no unused/commented out code
yep-> I have reviewed my code
yep-> I have fully tested my code

Finishes user story 60 card 10

---

app/controllers/admin/users_controller.rb
app/views/admin/users/index.html.erb
app/views/layouts/application.html.erb
config/routes.rb
spec/features/admins/admin_user_index_spec.rb

- rspec - 100%
Gives admins a nav bar link to user index page which lists info for all non admin/merchant users. 
Users names on the admin user index are links to their admin user shows, and each user has a button to upgrade them to a merchant (actual upgrade is in another story)
Wasn't too hard really, just jumped around in the project a bit
* description
closes user story 55
yep-> My code has no unused/commented out code
yep-> I have reviewed my code
- [] I have commented my code, …

Adds user story 55

---

app/controllers/cart_controller.rb
app/models/cart.rb
app/views/cart/index.html.erb
config/routes.rb
spec/features/cart/user_can_change_quantities_in_cart_spec.rb
spec/models/cart_spec.rb

- rspec - 100%
- rspec spec/models - 97.36% - Due to ApplicationController helper_methods. But I believe this is corrected in a new PR
Adds User Story 24, User can manipulate quantities in their cart.
- I had to hand-roll some not so RESTful routes here for the cart.  Let me know if you all have any suggestions on improving them.
* description
closes #52 
💩 💩 💩

Cart user can change quantities userstory24 #52

---

app/controllers/cart_controller.rb
app/models/cart.rb
app/views/cart/index.html.erb
config/routes.rb
spec/features/cart/user_can_change_quantities_in_cart_spec.rb
spec/features/cart/visitors_must_login_or_register_to_checkout_spec.rb
spec/features/navigation_bar_spec.rb
spec/models/cart_spec.rb

- rspec - 100%
- rspec spec/models - 97.36%
User Story 25 - Visitors see information telling me I must register or log in to finish the checkout process.
- I branched off my previous PR so please review/merge that one before this one: [link to old PR here](https://github.com/blake-enyart/little-coffee-shop/pull/121)
- Also revised a nav spec because the cart page has two places with links to login or register now.
* description
closes #51 

Visitors must login or register to checkout userstory25 #51

---

app/controllers/merchants_controller.rb
config/routes.rb

- rspec - x%
patch for dashboard route 
* description
closes #
👍

patch for dashboard route

---

app/controllers/admin/users_controller.rb
app/controllers/merchants_controller.rb
app/views/admin/users/show.html.erb
app/views/layouts/application.html.erb
app/views/merchants/index.html.erb
config/routes.rb
spec/features/merchants/merchants_index_page_spec.rb
spec/features/navigation_bar_spec.rb
spec/features/users_cannot_navigate_to_certain_paths_spec.rb

- rspec - 100%
admin merchant index
* description
closes #32 

Adds user story 41 and 38

---

app/views/merchants/index.html.erb

- rspec - x%
* description
closes #

Admin merchant index- small refactor

---

app/controllers/cart_controller.rb
app/controllers/orders_controller.rb
app/models/cart.rb
app/views/cart/index.html.erb
app/views/orders/index.html.erb
config/routes.rb
spec/features/cart/users_can_checkout_spec.rb
spec/models/cart_spec.rb

- rspec - 100%
- rspec spec/models - 97.75%
Added User Story 26, Registered users can check out
- Added @cart instance methods #empty_cart and #generate_order
- I was not sure where to put the #generate_order method, I chose the Cart.  But I could see it fitting in as an Order class method perhaps.
- I could not find a way around sending the current_user as an argument to generate_order.
* description
closes #50 
(because I watched Aquaman last night)

Registered users can checkout userstory26 #50

---

app/controllers/cart_controller.rb
app/controllers/orders_controller.rb
app/models/cart.rb
app/views/cart/index.html.erb
app/views/orders/index.html.erb
app/views/users/_show.html.erb
config/routes.rb
spec/features/cart/users_can_checkout_spec.rb
spec/features/reg_users/orders_show_spec.rb
spec/models/cart_spec.rb

- rspec - 100%
- rspec spec/models - 97.75%
User Story 27, User Profile displays Orders link
- I branched off my previous PR so that I could use the routing.  Please review the [previous PR first](https://github.com/blake-enyart/little-coffee-shop/pull/129)
* description
closes #48 

Userstory27 user profile displays orders links #48

---

app/assets/stylesheets/application.css
app/controllers/merchants_controller.rb
app/views/cart/index.html.erb
app/views/items/index.html.erb
app/views/merchants/index.html.erb
app/views/sessions/new.html.erb
app/views/users/_form.html.erb
spec/features/cart/view_cart_with_items_spec.rb

- rspec - 100%
more styling
cart styling still incomplete but need to merge to avoid further conflicts with code Mike is currently working on
Styling for visitor and user experiences
closes #
👍

Styling continued

---

app/controllers/merchants_controller.rb
app/models/order.rb
app/models/user.rb
app/views/merchants/show.html.erb
config/routes.rb
db/schema.rb
spec/features/merchants/show_spec.rb
spec/models/order_spec.rb
spec/models/user_spec.rb

- rspec - 100%
- rspec spec/models - 97.86%%
Create pending orders list on merchant dashboard
* Test development on both the features and models. I would like some review here.
* FactoryBot associations
* description
closes #39 
😠

Bte merchant dash orders us 35 issue #39

---

app/controllers/admin/base_controller.rb
app/controllers/admin/merchants_controller.rb
app/controllers/admin/users_controller.rb
app/controllers/application_controller.rb
app/controllers/orders_controller.rb
config/routes.rb

- rspec - 100%
Adds BaseController to control access to admin access pages
Implementation of 404 status code for routing
* description
closes #

Refactor to use admin base controller

---

app/assets/stylesheets/application.css
app/views/cart/index.html.erb
app/views/layouts/application.html.erb

- rspec - 100%
Cart visualization
cart layout was the hardest of all styling I've don so far
* description
closes #
:😅

basic Styling completed for cart

---

spec/features/admins/admin_user_index_spec.rb
spec/features/admins/admin_user_show_spec.rb

- rspec - 100%
Creates test for Admin User show page functionality
* description
closes #64 

Pass User Story 56 - Admin User Show Page Access

---

app/controllers/admin/users_controller.rb
config/routes.rb

- rspec - 100%
Removing the required id from the admin merchant path.
To accomplish this I-
1. changed the hand rolled route in routes
2. added a dashboard action to adminusers controller 
3. created dashboard view that is currently empty
* description
closes comments about my previous pr

Reverts admin dashboard path to previous path without id

---

app/views/cart/index.html.erb

- rspec - 100%
- rspec spec/models - 98.28%
Patch for Cart checkout, removes option for all users except registered user
* description
closes #
👍

fixes checkout issue for visitor

---

app/controllers/merchants/base_controller.rb
app/controllers/merchants/orders_controller.rb
app/models/user.rb
app/views/merchants/orders/show.html.erb
app/views/merchants/show.html.erb
config/routes.rb
spec/features/merchants/orders/show_spec.rb
spec/models/order_spec.rb

- rspec - 100%
- rspec spec/models - 98.28%
*Creates merchant base controller to protect nested item and order pages
*Edit to pending orders method to only return distinct orders
*Reordered routes to nest orders and items under merchant resource
Most of this.  The test setup was extremely difficult, the MVC is completely wrong on this, and the Merchant Order show action looks really rough. Basically this code looks bad, but I'm pretty done working on it.
* description
closes #19 

Pass User Story 52 - Merchant Sees Order Show Page

---

app/controllers/orders_controller.rb
app/models/item.rb
app/views/orders/show.html.erb
spec/features/reg_users/order_show_page_spec.rb
spec/models/item_spec.rb

- rspec - 100%
- rspec spec/models - 98.41%
User Order show page 
* description
closes #46 
👍

Order show page

---

app/controllers/merchants/items_controller.rb
app/views/merchants/items/index.html.erb
config/routes.rb
spec/features/merchants/merchant_disables_item_spec.rb

- rspec - 100%
- rspec spec/models - 98.28%
User Story 45, Merchant disables an item
* description
closes #27 

Merchant disables an item userstory45 #27

---

app/controllers/merchants/items_controller.rb
app/views/merchants/items/index.html.erb
config/routes.rb
spec/features/merchants/items_index_spec.rb

- rspec - 100%
- rspec spec/models - 98.28%
User Story 47, Merchant deletes an item
- Merchants can now delete items (as long as they have no orders)
* description
closes #25 

Merchant deletes an item userstory47 #25

---

app/controllers/admin/merchants_controller.rb
app/controllers/sessions_controller.rb
app/views/merchants/index.html.erb
config/routes.rb
spec/features/merchants/merchants_index_page_spec.rb

- rspec - 100%
Allows admins to disable merchants 
* description
closes #31 
-> I have commented my code, particularly in hard-to-understand areas

Disable merchant

---

app/controllers/merchants/items_controller.rb
app/models/item.rb
app/models/order_item.rb
app/views/merchants/orders/show.html.erb
config/routes.rb
spec/features/merchants/order_fullfillment_spec.rb
spec/models/item_spec.rb
spec/models/order_item_spec.rb

- rspec - 100%
User Story 53, Merchant fulfills part of an order
* description
closes #18

Merchant fullfills part of an order userstory53 #18

---

app/controllers/orders_controller.rb
app/views/orders/show.html.erb
config/routes.rb
spec/features/reg_users/cancel_order_spec.rb

- rspec - 100%
User Story 30, User cancels an order
- I will add to the issues list that this Order#update controller action should be refactored to model methods.  In the interest of time, I left it as is. I left lots of comments in the code explaining each step though.
* description
closes #45 

User cancels an order userstory30 #45

---

app/models/order.rb
spec/models/order_spec.rb

- rspec - 100%
If all order items are fulfilled out will change an order to packaged 
* description
closes #44 
-> I have commented my code, particularly in hard-to-understand areas

User story 31

---

app/controllers/admin/users_controller.rb
spec/features/admins/admin_user_show_spec.rb

- rspec - 100%
* Redirects to merchant dashboard when admin visits user show page that belongs to merchant
nada
* description
closes #12 

Pass User Story 58 - Admin Visiting Merchant on User Show redirects to Merchant Show

---

README.md

Changed the Github links to just be referenced to our names. I thought it looked better this way
- rspec - x%
* description
closes #

Cleaned up Github links

---

spec/features/merchants/cannot_fulfill_order_spec.rb

- rspec - 100%
- rspec spec/models - 98.74%
- Added spec for merchants being unable to fulfill items due to lack of inventory.
- Feature was already implemented in previous PR
* description
closes #17 

Added spec for merchant unable to fulfill item if lacking inventory

---

app/controllers/items_controller.rb
app/controllers/merchants/items_controller.rb
app/models/item.rb
app/views/merchants/items/index.html.erb
app/views/merchants/items/new.html.erb
config/routes.rb
spec/features/merchants/adds_items_spec.rb

- rspec - 100.00%
- rspec spec/models - 98.29%
Makes sure a merchant can only add an item if necessary fields are filled.
Testing an image within a css tag, ended up just testing the actual image_url attribute of the new item.
closes #23

Merchant add item missing fields us #49 issue 23

---

app/controllers/merchants_controller.rb
app/models/user.rb
app/views/merchants/show.html.erb
spec/features/merchants/dashboard_statistics_spec.rb
spec/models/user_spec.rb

- rspec - 100%
Paired this with Blake.  Not fully functional for the User Story 36, Merchant Dashboard Statistics.  Just wanted to upload it in case Blake or anyone wanted to attempt the others.
- ~~Only finished the top 5 items I have sold~~
- ~~started the next one for percentage of inventory sold~~
- Edit 635am, 4/11 - Added all statistics except for the city one
- top 3 city/state where my items were shipped, and their quantities (Springfield, MI should not be grouped with Springfield, CO)
* description
closes #

Merchant dashboard statistics #38

---

app/views/layouts/application.html.erb
config/routes.rb
spec/features/navigation_bar_spec.rb
spec/features/users/registration_spec.rb

- rspec - x%
* description
closes #

Registration URI hotfix

---

app/controllers/admin/users_controller.rb
app/views/admin/users/dashboard.html.erb
spec/features/admins/admin_shipped_order_spec.rb

- rspec - 100%
Hotfix for admin dashboard orders due to merge conflict
* description
closes #

Hotfix for admin dashboard orders due to merge conflict

---

app/controllers/sessions_controller.rb
app/views/users/_form.html.erb
app/views/users/edit.html.erb
app/views/users/new.html.erb
spec/features/admins/admin_user_show_spec.rb
spec/features/users/login_spec.rb
spec/features/users/logout_spec.rb

- rspec - 100%
* description
closes #

Bte hotfix

---

app/controllers/merchants/orders_controller.rb
app/views/merchants/orders/show.html.erb

- rspec - 100%
Refactored merchants/orders/show.html.erb & merchants/orders_controller.rb
- In controller, build hash with key=item_object, value=order_item_object
- This allows us to get rid of '.where' statements from the view"
* description
closes #

Refactored merchant order show page order_items

---

db/data/MOCK_DATA_merchants.csv
db/data/MOCK_DATA_users.csv
db/seeds.rb

- rspec - x%
Added seed data for coffee from [https://bluebottlecoffee.com/](https://bluebottlecoffee.com/).
I did a bit of randomness to the order generation, following the instructor's technique.  Keeps it interesting.
* description
closes #

Coffee seed data

---

app/controllers/cart_controller.rb

- rspec - 100%
Fixes bug: `On the cart show page, when you hit the maximum for an item you are no longer able to decrement that item count`
* description
closes #

Refactored card#decrement item to fix bug

---

README.md
app/views/welcome/index.html.erb

- rspec - x%
Added our info to the welcome page. Feel free to add anything else.
* description
closes #

Added our info to the welcome page
